#include "ClientConfig.h"

const int CHUNK_WINDOW_SIZE = 10;

const int REPLY_MAX_SIZE = 512;

const int CHUNK_QUEUE_THRESHOLD_SIZE = 100;

const double NUM_SECONDS_TO_WAIT_BETWEEN_QUEUE_THRESHOLD_CHECKING = 0.2;

const double NUM_SECONDS_TO_WAIT_FOR_NEXT_CHUNK = 0.2;
